name: Deploy Version

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  pull_request_review:
    types:
      - submitted

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release.outputs.version }}
      changelog: ${{ steps.release.outputs.changelog }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Release
        uses: ./.github/actions/github-version-release
        id: release
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}